language: erlang
matrix:
  include:
    - os: linux
      dist: xenial
      otp_release: 21.1
    - os: linux
      dist: xenial
      otp_release: 20.3.8.5
    - os: linux
      dist: xenial
      otp_release: 19.3
    - os: osx
      language: generic
before_script:
- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get -y update || true ; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install -y g++ make cmake libssl-dev libuv1-dev || true ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang libuv cmake openssl || true; fi
- curl https://s3.amazonaws.com/rebar3/rebar3 --output rebar3 && chmod +x rebar3
script:
    - ./rebar3 compile
